--
-- PostgreSQL database dump
--

\restrict KlVq4j6gGxm04LcxpmwNSUw9rAW0WhtItkIiUx8bK6efJUz9YY0JHcBI59yrhJk

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

-- Started on 2026-06-20 18:21:38

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 226 (class 1259 OID 17283)
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 17282)
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 17293)
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 17292)
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 17273)
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 17272)
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 17302)
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 17321)
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 17320)
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 17301)
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 17330)
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 17329)
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 17391)
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 17390)
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 17261)
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 17260)
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 17249)
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 17248)
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 246 (class 1259 OID 17511)
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- TOC entry 238 (class 1259 OID 17432)
-- Name: reviews_customer; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.reviews_customer (
    id bigint NOT NULL,
    first_name character varying(100),
    last_name character varying(100),
    purchase_count integer CONSTRAINT reviews_customer_purchase_number_not_null NOT NULL,
    phone_number character varying(11)
);


ALTER TABLE public.reviews_customer OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 17431)
-- Name: reviews_customer_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.reviews_customer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reviews_customer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 240 (class 1259 OID 17440)
-- Name: reviews_food; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.reviews_food (
    id bigint NOT NULL,
    name character varying(100),
    price integer NOT NULL,
    rating numeric(3,2),
    purchase_count integer
);


ALTER TABLE public.reviews_food OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 17439)
-- Name: reviews_food_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.reviews_food ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reviews_food_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 242 (class 1259 OID 17449)
-- Name: reviews_review; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.reviews_review (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    customer_id bigint NOT NULL
);


ALTER TABLE public.reviews_review OWNER TO postgres;

--
-- TOC entry 241 (class 1259 OID 17448)
-- Name: reviews_review_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.reviews_review ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reviews_review_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 245 (class 1259 OID 17470)
-- Name: reviews_reviewitem; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.reviews_reviewitem (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    first_time boolean NOT NULL,
    food_quality character varying(1) NOT NULL,
    food_size character varying(1) NOT NULL,
    food_price character varying(1) NOT NULL,
    review_text text,
    food_id bigint NOT NULL,
    review_id bigint NOT NULL
);


ALTER TABLE public.reviews_reviewitem OWNER TO postgres;

--
-- TOC entry 244 (class 1259 OID 17469)
-- Name: reviews_reviewitem_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.reviews_reviewitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reviews_reviewitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 243 (class 1259 OID 17457)
-- Name: reviews_servicereview; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.reviews_servicereview (
    review_id bigint NOT NULL,
    first_time boolean NOT NULL,
    duration character varying(1),
    service_quality character varying(1),
    review_text text
);


ALTER TABLE public.reviews_servicereview OWNER TO postgres;

--
-- TOC entry 5154 (class 0 OID 17283)
-- Dependencies: 226
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- TOC entry 5156 (class 0 OID 17293)
-- Dependencies: 228
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- TOC entry 5152 (class 0 OID 17273)
-- Dependencies: 224
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	3	add_permission
6	Can change permission	3	change_permission
7	Can delete permission	3	delete_permission
8	Can view permission	3	view_permission
9	Can add group	2	add_group
10	Can change group	2	change_group
11	Can delete group	2	delete_group
12	Can view group	2	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add customer	7	add_customer
26	Can change customer	7	change_customer
27	Can delete customer	7	delete_customer
28	Can view customer	7	view_customer
29	Can add food	8	add_food
30	Can change food	8	change_food
31	Can delete food	8	delete_food
32	Can view food	8	view_food
33	Can add review	9	add_review
34	Can change review	9	change_review
35	Can delete review	9	delete_review
36	Can view review	9	view_review
37	Can add service review	11	add_servicereview
38	Can change service review	11	change_servicereview
39	Can delete service review	11	delete_servicereview
40	Can view service review	11	view_servicereview
41	Can add review item	10	add_reviewitem
42	Can change review item	10	change_reviewitem
43	Can delete review item	10	delete_reviewitem
44	Can view review item	10	view_reviewitem
\.


--
-- TOC entry 5158 (class 0 OID 17302)
-- Dependencies: 230
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	pbkdf2_sha256$1200000$UrJwv0BXtujWixZtHS9cFs$3L80P5PyaYqfiGpcSMtIafIhdSOGkbWSz0VgFb5pgC4=	2026-06-20 00:13:14.15334+03:30	t	admin				t	t	2026-06-20 00:12:37.466105+03:30
\.


--
-- TOC entry 5160 (class 0 OID 17321)
-- Dependencies: 232
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- TOC entry 5162 (class 0 OID 17330)
-- Dependencies: 234
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- TOC entry 5164 (class 0 OID 17391)
-- Dependencies: 236
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2026-06-20 00:15:34.305196+03:30	1	Food object (1)	1	[{"added": {}}]	8	1
2	2026-06-20 00:15:56.93063+03:30	2	Food object (2)	1	[{"added": {}}]	8	1
3	2026-06-20 00:16:07.372304+03:30	3	Food object (3)	1	[{"added": {}}]	8	1
4	2026-06-20 00:19:18.185126+03:30	3	Food object (3)	3		8	1
5	2026-06-20 00:19:18.185213+03:30	2	Food object (2)	3		8	1
6	2026-06-20 00:19:18.18526+03:30	1	Food object (1)	3		8	1
7	2026-06-20 00:19:44.792271+03:30	4	Food object (4)	1	[{"added": {}}]	8	1
8	2026-06-20 00:19:55.404954+03:30	5	Food object (5)	1	[{"added": {}}]	8	1
9	2026-06-20 00:20:10.522552+03:30	6	Food object (6)	1	[{"added": {}}]	8	1
10	2026-06-20 15:06:29.658564+03:30	7	Food object (7)	1	[{"added": {}}]	8	1
11	2026-06-20 15:06:39.881269+03:30	8	Food object (8)	1	[{"added": {}}]	8	1
12	2026-06-20 15:06:45.941353+03:30	9	Food object (9)	1	[{"added": {}}]	8	1
13	2026-06-20 15:07:22.952796+03:30	10	Food object (10)	1	[{"added": {}}]	8	1
14	2026-06-20 15:07:31.64712+03:30	10	Food object (10)	2	[{"changed": {"fields": ["Price"]}}]	8	1
15	2026-06-20 15:07:37.794863+03:30	9	Food object (9)	2	[{"changed": {"fields": ["Price"]}}]	8	1
16	2026-06-20 15:07:58.636607+03:30	11	Food object (11)	1	[{"added": {}}]	8	1
17	2026-06-20 15:08:07.506786+03:30	8	Food object (8)	2	[{"changed": {"fields": ["Price"]}}]	8	1
18	2026-06-20 17:42:15.949306+03:30	52	Review object (52)	2	[]	9	1
\.


--
-- TOC entry 5150 (class 0 OID 17261)
-- Dependencies: 222
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	group
3	auth	permission
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	reviews	customer
8	reviews	food
9	reviews	review
10	reviews	reviewitem
11	reviews	servicereview
\.


--
-- TOC entry 5148 (class 0 OID 17249)
-- Dependencies: 220
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-06-19 18:57:16.506981+03:30
2	auth	0001_initial	2026-06-19 18:57:16.559582+03:30
3	admin	0001_initial	2026-06-19 18:57:16.575651+03:30
4	admin	0002_logentry_remove_auto_add	2026-06-19 18:57:16.580864+03:30
5	admin	0003_logentry_add_action_flag_choices	2026-06-19 18:57:16.586373+03:30
6	contenttypes	0002_remove_content_type_name	2026-06-19 18:57:16.59786+03:30
7	auth	0002_alter_permission_name_max_length	2026-06-19 18:57:16.603975+03:30
8	auth	0003_alter_user_email_max_length	2026-06-19 18:57:16.609784+03:30
9	auth	0004_alter_user_username_opts	2026-06-19 18:57:16.615383+03:30
10	auth	0005_alter_user_last_login_null	2026-06-19 18:57:16.62125+03:30
11	auth	0006_require_contenttypes_0002	2026-06-19 18:57:16.62222+03:30
12	auth	0007_alter_validators_add_error_messages	2026-06-19 18:57:16.627307+03:30
13	auth	0008_alter_user_username_max_length	2026-06-19 18:57:16.635257+03:30
14	auth	0009_alter_user_last_name_max_length	2026-06-19 18:57:16.641699+03:30
15	auth	0010_alter_group_name_max_length	2026-06-19 18:57:16.648937+03:30
16	auth	0011_update_proxy_permissions	2026-06-19 18:57:16.65449+03:30
17	auth	0012_alter_user_first_name_max_length	2026-06-19 18:57:16.6606+03:30
18	reviews	0001_initial	2026-06-19 18:57:16.693969+03:30
19	sessions	0001_initial	2026-06-19 18:57:16.701107+03:30
20	reviews	0002_alter_customer_phone_number	2026-06-19 23:57:54.603985+03:30
21	reviews	0003_rename_purchase_number_customer_purchase_count	2026-06-20 00:07:45.209367+03:30
22	reviews	0004_alter_food_rating_alter_reviewitem_food_price_and_more	2026-06-20 10:26:52.255859+03:30
23	reviews	0005_alter_servicereview_duration	2026-06-20 10:55:20.197474+03:30
24	reviews	0006_alter_servicereview_service_quality	2026-06-20 10:58:17.731623+03:30
25	reviews	0007_food_purchase_count	2026-06-20 12:44:09.832789+03:30
26	reviews	0008_alter_food_rating	2026-06-20 15:15:33.731464+03:30
27	reviews	0009_alter_food_options_alter_review_options_and_more	2026-06-20 18:09:32.216742+03:30
\.


--
-- TOC entry 5174 (class 0 OID 17511)
-- Dependencies: 246
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
bh3eorrco1hr0g1rsiumsgozj1t0q3dz	.eJxVjEEKwyAQAP-y5xA0akk89t4XlCKru2nSBgU1DaX07yWQS68zw3yAY81vh8uSNiawNa_cgMO1Tm4tnN1MYEHCH_MYnhx3QQ-M99SGFGuefbsn7WFLe0nEy_lo_wYTlgksaOGVMoaFkipIMt0gcAzeSK0YeTgFo4QUnRa6RxoHqbEn6tFrEp3hUUMDhRcOlcmNKVEBe701ENacOVaX-TXzBtZ03x9r3U2I:1wawBQ:DDxvyoQwXXsl9xbCaTvgNHQASEYSzjYYoL8NOdXklJA	2026-07-04 17:26:28.693187+03:30
\.


--
-- TOC entry 5166 (class 0 OID 17432)
-- Dependencies: 238
-- Data for Name: reviews_customer; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.reviews_customer (id, first_name, last_name, purchase_count, phone_number) FROM stdin;
\.


--
-- TOC entry 5168 (class 0 OID 17440)
-- Dependencies: 240
-- Data for Name: reviews_food; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.reviews_food (id, name, price, rating, purchase_count) FROM stdin;
10	کوکو سبزی	150	0.00	0
8	زرشک پلو با مرغ	250	0.00	0
7	خوراک کوبیده	250	3.00	3
9	همبرگر کلاسیک	450	4.33	4
11	تخم مرغ سوسیس	170	3.00	1
\.


--
-- TOC entry 5170 (class 0 OID 17449)
-- Dependencies: 242
-- Data for Name: reviews_review; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.reviews_review (id, created_at, customer_id) FROM stdin;
\.


--
-- TOC entry 5173 (class 0 OID 17470)
-- Dependencies: 245
-- Data for Name: reviews_reviewitem; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.reviews_reviewitem (id, quantity, first_time, food_quality, food_size, food_price, review_text, food_id, review_id) FROM stdin;
\.


--
-- TOC entry 5171 (class 0 OID 17457)
-- Dependencies: 243
-- Data for Name: reviews_servicereview; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.reviews_servicereview (review_id, first_time, duration, service_quality, review_text) FROM stdin;
\.


--
-- TOC entry 5180 (class 0 OID 0)
-- Dependencies: 225
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- TOC entry 5181 (class 0 OID 0)
-- Dependencies: 227
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- TOC entry 5182 (class 0 OID 0)
-- Dependencies: 223
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 44, true);


--
-- TOC entry 5183 (class 0 OID 0)
-- Dependencies: 231
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- TOC entry 5184 (class 0 OID 0)
-- Dependencies: 229
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 1, true);


--
-- TOC entry 5185 (class 0 OID 0)
-- Dependencies: 233
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- TOC entry 5186 (class 0 OID 0)
-- Dependencies: 235
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 18, true);


--
-- TOC entry 5187 (class 0 OID 0)
-- Dependencies: 221
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 11, true);


--
-- TOC entry 5188 (class 0 OID 0)
-- Dependencies: 219
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 27, true);


--
-- TOC entry 5189 (class 0 OID 0)
-- Dependencies: 237
-- Name: reviews_customer_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.reviews_customer_id_seq', 8, true);


--
-- TOC entry 5190 (class 0 OID 0)
-- Dependencies: 239
-- Name: reviews_food_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.reviews_food_id_seq', 11, true);


--
-- TOC entry 5191 (class 0 OID 0)
-- Dependencies: 241
-- Name: reviews_review_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.reviews_review_id_seq', 52, true);


--
-- TOC entry 5192 (class 0 OID 0)
-- Dependencies: 244
-- Name: reviews_reviewitem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.reviews_reviewitem_id_seq', 11, true);


--
-- TOC entry 4938 (class 2606 OID 17427)
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- TOC entry 4943 (class 2606 OID 17348)
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- TOC entry 4946 (class 2606 OID 17300)
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 4940 (class 2606 OID 17289)
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- TOC entry 4933 (class 2606 OID 17339)
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- TOC entry 4935 (class 2606 OID 17281)
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- TOC entry 4954 (class 2606 OID 17328)
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- TOC entry 4957 (class 2606 OID 17363)
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- TOC entry 4948 (class 2606 OID 17317)
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- TOC entry 4960 (class 2606 OID 17337)
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 4963 (class 2606 OID 17377)
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- TOC entry 4951 (class 2606 OID 17420)
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- TOC entry 4978 (class 2606 OID 17487)
-- Name: reviews_reviewitem composite_id; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reviews_reviewitem
    ADD CONSTRAINT composite_id UNIQUE (review_id, food_id);


--
-- TOC entry 4966 (class 2606 OID 17404)
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- TOC entry 4928 (class 2606 OID 17271)
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- TOC entry 4930 (class 2606 OID 17269)
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- TOC entry 4926 (class 2606 OID 17259)
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- TOC entry 4985 (class 2606 OID 17520)
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- TOC entry 4969 (class 2606 OID 17438)
-- Name: reviews_customer reviews_customer_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reviews_customer
    ADD CONSTRAINT reviews_customer_pkey PRIMARY KEY (id);


--
-- TOC entry 4971 (class 2606 OID 17447)
-- Name: reviews_food reviews_food_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reviews_food
    ADD CONSTRAINT reviews_food_pkey PRIMARY KEY (id);


--
-- TOC entry 4974 (class 2606 OID 17456)
-- Name: reviews_review reviews_review_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reviews_review
    ADD CONSTRAINT reviews_review_pkey PRIMARY KEY (id);


--
-- TOC entry 4981 (class 2606 OID 17485)
-- Name: reviews_reviewitem reviews_reviewitem_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reviews_reviewitem
    ADD CONSTRAINT reviews_reviewitem_pkey PRIMARY KEY (id);


--
-- TOC entry 4976 (class 2606 OID 17468)
-- Name: reviews_servicereview reviews_servicereview_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reviews_servicereview
    ADD CONSTRAINT reviews_servicereview_pkey PRIMARY KEY (review_id);


--
-- TOC entry 4936 (class 1259 OID 17428)
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- TOC entry 4941 (class 1259 OID 17359)
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- TOC entry 4944 (class 1259 OID 17360)
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- TOC entry 4931 (class 1259 OID 17345)
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- TOC entry 4952 (class 1259 OID 17375)
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- TOC entry 4955 (class 1259 OID 17374)
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- TOC entry 4958 (class 1259 OID 17389)
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- TOC entry 4961 (class 1259 OID 17388)
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- TOC entry 4949 (class 1259 OID 17421)
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- TOC entry 4964 (class 1259 OID 17415)
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- TOC entry 4967 (class 1259 OID 17416)
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- TOC entry 4983 (class 1259 OID 17522)
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- TOC entry 4986 (class 1259 OID 17521)
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- TOC entry 4972 (class 1259 OID 17493)
-- Name: reviews_review_customer_id_17e79eab; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX reviews_review_customer_id_17e79eab ON public.reviews_review USING btree (customer_id);


--
-- TOC entry 4979 (class 1259 OID 17509)
-- Name: reviews_reviewitem_food_id_fddc81a3; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX reviews_reviewitem_food_id_fddc81a3 ON public.reviews_reviewitem USING btree (food_id);


--
-- TOC entry 4982 (class 1259 OID 17510)
-- Name: reviews_reviewitem_review_id_e3ed2353; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX reviews_reviewitem_review_id_e3ed2353 ON public.reviews_reviewitem USING btree (review_id);


--
-- TOC entry 4988 (class 2606 OID 17354)
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4989 (class 2606 OID 17349)
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4987 (class 2606 OID 17340)
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4990 (class 2606 OID 17369)
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4991 (class 2606 OID 17364)
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4992 (class 2606 OID 17383)
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4993 (class 2606 OID 17378)
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4994 (class 2606 OID 17405)
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4995 (class 2606 OID 17410)
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4996 (class 2606 OID 17488)
-- Name: reviews_review reviews_review_customer_id_17e79eab_fk_reviews_customer_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reviews_review
    ADD CONSTRAINT reviews_review_customer_id_17e79eab_fk_reviews_customer_id FOREIGN KEY (customer_id) REFERENCES public.reviews_customer(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4998 (class 2606 OID 17499)
-- Name: reviews_reviewitem reviews_reviewitem_food_id_fddc81a3_fk_reviews_food_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reviews_reviewitem
    ADD CONSTRAINT reviews_reviewitem_food_id_fddc81a3_fk_reviews_food_id FOREIGN KEY (food_id) REFERENCES public.reviews_food(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4999 (class 2606 OID 17504)
-- Name: reviews_reviewitem reviews_reviewitem_review_id_e3ed2353_fk_reviews_review_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reviews_reviewitem
    ADD CONSTRAINT reviews_reviewitem_review_id_e3ed2353_fk_reviews_review_id FOREIGN KEY (review_id) REFERENCES public.reviews_review(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4997 (class 2606 OID 17494)
-- Name: reviews_servicereview reviews_servicereview_review_id_08c73d6f_fk_reviews_review_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reviews_servicereview
    ADD CONSTRAINT reviews_servicereview_review_id_08c73d6f_fk_reviews_review_id FOREIGN KEY (review_id) REFERENCES public.reviews_review(id) DEFERRABLE INITIALLY DEFERRED;


-- Completed on 2026-06-20 18:21:38

--
-- PostgreSQL database dump complete
--

\unrestrict KlVq4j6gGxm04LcxpmwNSUw9rAW0WhtItkIiUx8bK6efJUz9YY0JHcBI59yrhJk

