# Generated by Django 6.0.6 on 2026-06-19 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_number', models.IntegerField(default=0)),
                ('phone_number', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reviews.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceReview',
            fields=[
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='reviews.review')),
                ('first_time', models.BooleanField(default=True)),
                ('duration', models.CharField(choices=[('S', 'Slower than expected'), ('E', 'As expected'), ('F', 'Faster than expected')], default='E', max_length=1)),
                ('service_quality', models.CharField(choices=[('E', 'Excellent'), ('G', 'Good'), ('M', 'Medium'), ('B', 'Bad'), ('T', 'Terrible')], default='M', max_length=1)),
                ('review_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ReviewItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('first_time', models.BooleanField(default=True)),
                ('food_quality', models.CharField(choices=[('E', 'Excellent'), ('G', 'Good'), ('M', 'Medium'), ('B', 'Bad'), ('T', 'Terrible')], default='M', max_length=1)),
                ('food_size', models.CharField(choices=[('G', 'Good'), ('M', 'Medium'), ('B', 'Bad')], default='A', max_length=1)),
                ('food_price', models.CharField(choices=[('I', 'Inexpensive'), ('W', 'Well priced'), ('E', 'Expensive')], default='W', max_length=1)),
                ('review_text', models.TextField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reviews.food')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.review')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('review', 'food'), name='composite_id')],
            },
        ),
    ]
