# Generated by Django 6.0.6 on 2026-06-19 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_customer_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='purchase_number',
            new_name='purchase_count',
        ),
    ]
