# Generated by Django 6.0.6 on 2026-06-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_rename_purchase_number_customer_purchase_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='rating',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='reviewitem',
            name='food_price',
            field=models.CharField(blank=True, choices=[('I', 'Inexpensive'), ('W', 'Well priced'), ('E', 'Expensive')], default='W', max_length=1),
        ),
        migrations.AlterField(
            model_name='reviewitem',
            name='food_quality',
            field=models.CharField(blank=True, choices=[('E', 'Excellent'), ('G', 'Good'), ('M', 'Medium'), ('B', 'Bad'), ('T', 'Terrible')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='reviewitem',
            name='food_size',
            field=models.CharField(blank=True, choices=[('G', 'Good'), ('M', 'Medium'), ('B', 'Bad')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='reviewitem',
            name='review_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicereview',
            name='review_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
