# Generated by Django 6.0.6 on 2026-06-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_food_rating_alter_reviewitem_food_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicereview',
            name='duration',
            field=models.CharField(choices=[('S', 'Slower than expected'), ('E', 'As expected'), ('F', 'Faster than expected')], default='E', max_length=1, null=True),
        ),
    ]
