# Generated by Django 6.0.6 on 2026-06-20 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_servicereview_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicereview',
            name='service_quality',
            field=models.CharField(choices=[('E', 'Excellent'), ('G', 'Good'), ('M', 'Medium'), ('B', 'Bad'), ('T', 'Terrible')], default='M', max_length=1, null=True),
        ),
    ]
