# Generated by Django 6.0.6 on 2026-06-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_alter_servicereview_service_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='purchase_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
