# Generated by Django 6.0.6 on 2026-06-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_alter_food_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'verbose_name': 'غذا', 'verbose_name_plural': 'غذاها'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'نظرسنجی', 'verbose_name_plural': 'نظرسنجی\u200cها'},
        ),
        migrations.AlterField(
            model_name='reviewitem',
            name='food_size',
            field=models.CharField(blank=True, choices=[('G', 'Generous'), ('A', 'Adequate'), ('S', 'Small')], default='A', max_length=1),
        ),
    ]
